### ISSUE TITLE
[Help] Ubuntu enviroment

### ISSUE THREAD

**Issue by wta12** [NREL/EnergyPlusRegressionTool#26]
Hi @Myoldmopar 
I want to try  EPRegressionTool. Could you give me more info about the environment - Ubuntu and Python version, code editor? I have too much python installs on my Window so I would plan to use VMware this time. While the VM would be much more weaken than real PC, the development environment info would be very critical for me when It's my first time on Linux. I am using Python 3.5 now and wonder what is the main issue with Python higher than 3.4? Could I try to use it with Python 3.5? 
Thanks,
Khanh

**Comment by Myoldmopar** [comment]
Hi @wta12 did you see the information in the README?  I laid out the install steps pretty well there for Ubuntu.  I think on Ubuntu, Python 3.5 is fine. With Windows, if you follow my instructions and use the GObject installer, you can't use Python 3.5 because the GObject installer isn't set up to find anything above 3.4.

If you have specific problems, let me know, or open a new issue, though this is just a complete side project so I don't get to spend much time on it...
