### ISSUE TITLE
Windows GTK GUI needs python 3.4 other scripts need 3.5 or higher?

### ISSUE THREAD

**Issue by EnergyArchmage** [NREL/EnergyPlusRegressionTool#52]
I have been trying to move from https://github.com/NREL/EnergyPlusDevSupport to https://github.com/NREL/EnergyPlusRegressionTool for local test suite runs.  

In following instructions at https://github.com/NREL/EnergyPlusRegressionTool#windows I get to a point in the installation where installing the requirements (C:\Python34\Scripts\pip3.exe install -r requirements.txt) it fails on needing python 3.5 or higher.  

It seems PyOBject is abandoned at python 3.4 (no higher) while the regression scripts are moving on and requiring later python.  

Is the GUI still working on other platforms? Any suggestions for windows?

here is the traceback I am getting
![image](https://user-images.githubusercontent.com/8754769/76101713-1aecad00-5f8c-11ea-9216-8092a9e9694a.png)

**Comment by Myoldmopar** [comment]
The GUI works fine on all the platforms.  I think I had a comment in there about the Python version needing to be <= 3.4, but that is just an accident.  You should use the latest version you can.  The underlying code (non-gui) is [tested](https://github.com/NREL/EnergyPlusRegressionTool/blob/master/.travis.yml#L26) on Python 3.5 and 2.7 since I wanted it to be 2/3 compatible.  Now that we are in 2020 and 2.x has no support, I should probably take the 2.7 off.

I think if you just install a more recent Python (which you will want if you are building python-linked-eplus) you will be good to go.

**Comment by EnergyArchmage** [comment]
I did first try to install PyGObject with Python 3.8, which I do have, and it did not work.  I had to install python 3.4 to install PyGObject.  The <= 3.4 requirement is strait from the PyGObject site and I doubt it is an accident.
